name: generate
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: false
      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cache/go-build
            /home/runner/go/pkg/mod
            /home/runner/go/bin
          key: ${{ runner.os }}-${{ github.ref_name }}-${{ github.workflow }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.base_ref }}-${{ github.workflow }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
      - name: install proto-tools
        run: make proto-tools
      - name: buf generate
        run: make buf-generate
      - name: no diff verification
        run: |
          git diff --exit-code
          if [ $? -ne 0 ]; then
            echo "Generated files differ from committed files. Please run 'make buf-generate' and commit the changes."
            exit 1
          fi
