name: lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  proto:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: install tools
        run: make proto-tools
      - name: buf lint
        run: make buf-lint
      - name: AIP lint
        run: make api-lint
